### PR TITLE
Feature/topic area

### PR DESCRIPTION
**Pull request by GeorgDangl**
As discussed in the telecon on 10.10.2016

### CODE REVIEW

**Comment by GeorgDangl** [comment]
See https://github.com/BuildingSMART/BCF-API/pull/84 in the BCF API repository

**Comment by GeorgDangl** [comment]
Removed the milestone label as it's still under discussion

**Comment by pbuts** [comment]
Argumentation for the request to have an TopicArea and example areas:

We (KUBUS) have got many users request for area as a topic-property for fitering issues. Is a project specific geometrical part of the building like wing, sub-project, story, etc.

It should be added as and element to the Topic element in the markup and added to the extension scheme to provide a list of enumeration values
enumeration value="Shops"
enumeration value="Offices"
enumeration value="Appartments"
enumeration value="General"

**Comment by GeorgDangl** [comment]
We've got something for custom properties in the BCF API: https://github.com/buildingSMART/BCF-API/issues/219

**Comment by GeorgDangl** [comment]
The implementation in the API is here: https://github.com/buildingSMART/BCF-API/pull/222

**Comment by ykulbak** [comment]
Discussed on the group call on Sep 25th 2023. 

- This requirement can be met by adding custom properties (albeit in BCF API). See https://github.com/buildingSMART/BCF-API/issues/219; 
- Adding custom properties in XML is not technically sound since the properties are controlled by the sever
- We expect custom properties to be available in BCF 4.0

The group agreed to close this requiest.

**Pull request closed without merging**
