### PR TITLE
Fix BCF 2.1 non-compliant test cases

### PR DESCRIPTION
**Pull request by Moult**
Things like missing `Comment` or `CreationAuthor`. Minor things, but cause failures when automatic parsing against the XSD is done.

### CODE REVIEW

**Comment by Moult** [comment]
Just a quick note to _not_ merge this PR until later, as it seems there may be quite a few more issues to resolve first. Commit 046c71a recreates the viewpoints with orthogonal direction and up vectors (previously, they were not orthogonal). As a result, the snapshot images have also been replaced.

Currently on the to-do list:

 - Fix orthogonal viewpoint vector in "ComponentSelection" test case
 - Fix orthogonal viewpoint vector in "PerspectiveCamera" test case
 - Fix missing snapshot.png in "MaximumInformation" test case for BCF 1.0 compat
 - Fix missing snapshot.png in "ComponentSelection" test case for BCF 1.0 compat
 - Fix missing snapshot.png in "OrthogonalCamera" test case for BCF 1.0 compat
 - Fix missing snapshot.png in "PerspectiveCamera" test case for BCF 1.0 compat

More may appear.

**Comment by Moult** [comment]
I note that there is inconsistency in the test cases on how they refer to the schema. For example, the specification notes in `bcf.version`:

```
<Version VersionId="2.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="version.xsd">
```

Apart from the missing `version.xsd`, which I have noted in bug #188 - the reference to namespaces and schemas seem correct. However, in a variety of test cases, the reference to namespaces and schemas are not quite correct, I believe. For instance, this code sample in one of the test cases:

```
<Version VersionId="2.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="version.xsd">
```

In this case, the `schemaLocation` attribute is used, which should legally contain a whitespace separated namespace and schema pair. As BCF does not have its own namespace (should it? Perhaps another topic of discussion?) this is invalid XML.

Another example:

```
<Version VersionId="2.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
```

In this case, it is valid XML, but it defines the `xsd` namespace which is never used, and never references the schema. Although valid, is probably not best practices.

If others agree, I will make a list of all these occurrences and standardise them across the test cases. Note that although the examples given are just about the version element, the same issue is seen across all files.

**Comment by Moult** [comment]
Another issue is the use of the `standalone` attribute which is seen in some test cases:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
```

No DTD is used, only schema definitions, so I believe the `standalone="yes"` attribute (although benign if it exists) should be removed to represent best practice. If others agree, I will add it to this PR.

**Comment by Moult** [comment]
In addition, the documentation states:

> It is possible to store additional files in the BCF zip container as documents. These files can be referenced by other files via their relative paths. It is recommended to put them in a folder called Documents in the root folder of the zip archive.

None of the test cases follow this recommendation. I recommend first seeing what vendors are doing, and if vendors follow it, fix the test cases. If vendors don't follow it, remove the line from the documentation.

**Comment by Moult** [comment]
Also, the documentation refers to the attribute `IsExternal` in CapsCase.

The specification defines it as `isExternal` in camelCase.

All element and attribute names in the specification are CapsCase, _except_ for `isExternal`, which breaks the convention. If I were not concerned for case sensitive vendor implementations, I would push for standardising CapsCase.

**Comment by Moult** [comment]
I would propose to fix the bitmap reference to be relative to the topic dir, as per #180 .

**Comment by Moult** [comment]
One more thing to discuss - screenshots don't show everything, like Lines or Bitmaps, or ClippingPlanes, should this be the case?

**Review by GeorgDangl — APPROVED** [review]

**Pull request merged**
