### PR TITLE
Feature/test case checking

### PR DESCRIPTION
**Pull request by GeorgDangl**
This adds a GitHub Action that automatically calls the tool from @CBenghi whenever there is a change in the `Test Cases` folder.

You can manually invoke the checking on any OS by running `./build.cmd CheckTestCases` at the repository root.

The action itself fails, since there are a lot of errors in the test cases😀 See here for the runs:
https://github.com/buildingSMART/BCF-XML/actions

### CODE REVIEW

**Comment by GeorgDangl** [comment]
There's some more discussion in #317

**Comment by CBenghi** [comment]
Hi @GeorgDangl,

I've pushed an update to the tool that should solve the problem with the unmanaged exception.
it was due to different case sensitivity in linux/windows on the filesystem.

Let me know if it gets better, I've tried id with WSL, and the test of image size fails, but it's handled.
I'm curious to see what happens next.

**Comment by GeorgDangl** [comment]
Sorry for going back and forth with that one commit, but I've configure the check to only run for changes in the `Test Cases/*` directory, so I need to change that to be able to try it out😀

**Comment by GeorgDangl** [comment]
Hey @CBenghi, looks fine now! The test fails, as expected, but the tool itself runs through and reports error code 24: https://github.com/buildingSMART/BCF-XML/actions/runs/637264703

So imho this is ready for merging.

Thank you again for providing the tool!

**Comment by CBenghi** [comment]
@GeorgDangl no, thank you for integrating it.
I would have had no idea, never used nuke before.
This is brilliant!

**Pull request merged**
