### PR TITLE
Feature/multiple comment viewpoint

### PR DESCRIPTION
**Pull request by linhard**
Allow multiple viewpoints on comments

### CODE REVIEW

**Comment by ErikPijnenburg** [comment]
Multiple viewpoints per comment was discussed long time ago and decided not to do.
Multiple comments per viewpoints are allowed

**Comment by GeorgDangl** [comment]
Decided to not include

**Comment by vulevukusej** [comment]
Out of curiosity, what was the reasoning behind not supporting this?

**Comment by GeorgDangl** [comment]
I'm not sure I remember correctly, but I think it was to keep complexity low.

**Comment by vulevukusej** [comment]
I think it's an interesting omission.  Some topics are difficult to capture with only words + 1 viewpoint.  The user is then forced to create additional comments with additional viewpoints, thus polluting the comment thread and arguably increasing complexity for the user..

**Comment by GeorgDangl** [comment]
I just checked, this came up recently, too: https://github.com/buildingSMART/BCF-API/issues/283

I think there wasn't a strong push for having this feature, so that's why it was closed again. But, the API is a community effort, so if we can make a good argument for it, it's always possible to include it in future versions😀

If you want to join the discussion, you can send us an email at opencde@buildingsmart.org, we're having a call every second Monday at 11:00 CET.

**Pull request closed without merging**
