### PR TITLE
Initial documentation for `ServerAssignedId`.

### PR DESCRIPTION
**Pull request by CBenghi**
Initial documentation feels ok around ServerAssignedId.

I've also added a type: NonWhiteSpaceString to the xsd (not convinced with the name, if  nothing else for consistency).

### CODE REVIEW

**Comment by cschladetsch** [comment]
NonEmptyString (rather than NonWhiteSpaceString) is quite conformal I think, but could simply be trying to split hairs.

**Comment by CBenghi** [comment]
@cschladetsch I've thought about that, but technically the xsd constraint collapses whitespaces.
Similarly, for example, `.NET` distinguishes between `string.IsNullOrEmpty()` and `string.IsNullOrWhiteSpace() `.

**Comment by cschladetsch** [comment]
@CBenghi good catch, however doesn't that support the case for using NonEmptyString? Given that Xsd constraints already collapses whitespace.

**Comment by CBenghi** [comment]
Yes, I'm sold.

**Pull request merged**
