### PR TITLE
Test case: Topics with different models

### PR DESCRIPTION
**Pull request by jasollien**

### CODE REVIEW

**Comment by pasi-paasiala** [comment]
This would mean that everything, for example, in the MEP model should be visible and nothing else, when the MEP model is the only entry in the Files. I kind of get the point, but this is pushing the BCF envelope. Let's hear comments from the others.

**Comment by GeorgDangl** [comment]
Looks good for me. The behavior should be that the client switches between the models when different topics are opened, right?

**Comment by pasi-paasiala** [comment]
After thinking about this a bit longer, I see the following aspects in this:

Pros:
* Simple way to display one or multiple models properly
* User will be made aware of the models that should be available to visualize a topic
* When topic comes a server, the model references can be stored in the client, so that new topics will have proper references

Cons:
* Add complexity to implementation: Need to implement a mapping from File entries to imported models

**Comment by jasollien** [comment]
Thanks for the input. The main motivation behind this test is just for us to actually test if the "file" principle works

https://github.com/buildingSMART/BCF-API/issues/269

**Review by GeorgDangl — APPROVED** [review]

**Pull request merged**
