### PR TITLE
Viewpoint changes to 2.2

### PR DESCRIPTION
**Pull request by CBenghi**
Hello all and @ykulbak,

I've put together a bit of documentation that should capture what was said in the call.

In the production of the document I've added two small changes to what was agreed, which I hope make sense and improve the format with no drawbacks:

1. I've added an optional `nearPlane` value to the fields, and a few notes that allow simple implementation, however the docs state that its evaluation is not enforced in the current version so that we can discuss the issues raised in greater detail.
2. I've set the `AspectRatio` default to 1.0 instead of 4/3 as suggested in the call, because it better reflects the current state of the industry.

Please let me know your comments.

You can see the updated readme on my fork at: https://github.com/CBenghi/BCF-XML/blob/release_2_2/Documentation/README.md

Best,
Claudio

### CODE REVIEW

**Comment by ykulbak** [comment]
@CBenghi thank you! 
I thought we agreed that for BCF 2.2 a NearPlan will not be specified and the AspectRatio is optional?

**Comment by CBenghi** [comment]
Sorry, a few misunderstandings there... I missed the optional nature of
ratio.

As I was writing the doc I thought they are both truly critical to
determine visibility.

Ratio feels super trivial to implement, so since every one is touching the
code it made sense to have it.

Near plane less trivial so it's not enforced, but I don't see why not
having it as optional.

I'm fine with making ratio optional too if it helps.

So the minimum effort for compliance would be to interpret the scaling
factors correctly, but the possibility is to make it work right in the
weeks to come.

Does it make sense?

Claudio

Il Ven 30 Ott 2020, 02:51 Yoram Kulbak <notifications@github.com> ha
scritto:

**Comment by ykulbak** [comment]
@CBenghi I'm not sure. I think in the meeting there was a strong desire to defer requiring the near plane to a future release. Also, for AspectRatio we agreed on a default value of 4:3 and not 1.0? I'll let others comment

**Comment by pasi-paasiala** [comment]
I also don't think we should have near plane defined. In Solibri we have a setting for it defaulting to 0.1m. If this was defined in a viewpoint and for some reason, it would be a large value, say 10m, our users might be confused when navigation, since they wouldn't see thing in the way they've been expecting. In general, I don't think this has been a big problem.

**Comment by mattikannala** [comment]
There is one spelling error: "simmetric"

**Comment by CBenghi** [comment]
> Also, for AspectRatio we agreed on a default value of 4:3 and not 1.0? I'll let others comment

Yes, we did.

As I was writing up, though, I realised that this might disadvantage some old implementations against others.
Since some stored height and some width it made sense to set the aspect to 1:1 to even out the differences, 

I took the liberty to make it 1:1 because it think it was me arguing in favour of 4:3.

Happy to change it to 4:3 if it's preferred. Please add your comments here.

In the meantime I'll remove the spec for nearPlane an fix the typo that @mattikannala noticed.

**Comment by mattikannala** [comment]
Not fully sure, but I think the near and far plane should match the frustum near and far in the picture:

image

**Comment by CBenghi** [comment]
> Not fully sure, but I think the near and far plane should match the frustum near and far in the picture:
> 
@mattikannala I'm not sure I get what your objection is. In my intention they do. Is the presentation not clear?

**Comment by mattikannala** [comment]
> > Not fully sure, but I think the near and far plane should match the frustum near and far in the picture:
> 
> @mattikannala I'm not sure I get what your objection is. In my intention they do. Is the presentation not clear?

Edited picture a bit. See dark green lines that now matches with the frustum planes.

image

**Comment by CBenghi** [comment]
@ykulbak, @pasi-paasiala,

I've retracted the proposal for the NearPlane field in the docs and xsd. 
The other difference to what agreed is the default of 1:1 vs 4:3 for the aspect ratio when reading old files.

I still think 1:1 would result in better conversions, but I'm happy to quickly fix that if you hold different views.

@mattikannala the `CameraDirection` vector aims at the center of the front and back planes, not at the lower edge, that's why the dimension lines reach them in the center of the vertical edges. I'll try to see if I can make that clearer in the graphics.

**Comment by CBenghi** [comment]
@mattikannala, I've updated the graphics to make it clearer. Is this any better?

**Review by ykulbak — APPROVED** [review]

**Comment by ykulbak** [comment]
Comments in the group discussion:
1. adjust field of view illustration and verbal explanation to clarify that it applies for the whole vertical field of view (rather than half)

**Comment by CBenghi** [comment]
Hi All, I've added the clarification decided in the call.
@pasi-paasiala and @jasollien, can you approve the final state?

**Review by pasi-paasiala — APPROVED** [review]

**Comment by ykulbak** [comment]
@CBenghi I'm sorry, can you please rebase the latest `release_2_2` branch changes? Unfortunately the recent change to replace tabs with spaces has created a merge conflict.

**Comment by CBenghi** [comment]
Hi @ykulbak,
I've done that. It should be ok now.
Best,
Claudio

**Pull request merged**
