### PR TITLE
Markup schema fix for recurring elements

### PR DESCRIPTION
**Pull request by venilillkall**
BIMSnippet to unbounded, remove plural from DocumentReferences and Relatedtopics element names. Maybe this is the original intent?

### CODE REVIEW

**Comment by GeorgDangl** [comment]
Hi, I like both commits, but we should keep them on a new branch for a future release since the current standard is fixed as-is.

**Comment by venilillkall** [comment]
Ok. Found one more similar issue in visinfo.xsd - fix is also included here.
Something I should do?

**Comment by GeorgDangl** [comment]
There's nothing you have to do right now, we'll have a telecon at 28.09.about the specification and then decide on what to do next. You may join us if you want, please contact me at dangl@iabi.eu.

**Comment by GeorgDangl** [comment]
Accepted for 2.1 / Will overhaul all schemas (iabi)

**Pull request merged**
