### PR TITLE
Feature/due date

### PR DESCRIPTION
**Pull request by linhard**
Added DueDate to topic

### CODE REVIEW

**Comment by GeorgDangl** [comment]
There should be an additional property to indicate a `Finished` state on a topic if there's a `DueDate` property.

**Comment by CapnK** [comment]
Isn't that 'Finished' property the same as setting the TopicStatus = 'Closed'
(or another appropriate value in the extension schema)

**Comment by pasi-paasiala** [comment]
I agree with @CapnK. We don't need another status.

**Comment by GeorgDangl** [comment]
Accept for 2.1

**Pull request merged**
