### PR TITLE
Feature/milestone

### PR DESCRIPTION
**Pull request by GeorgDangl**
As discussed in the telecon on 10.10.2016

### CODE REVIEW

**Comment by GeorgDangl** [comment]
See https://github.com/BuildingSMART/BCF-API/pull/82 in the BCF API repository

**Comment by mullerlele** [comment]
Per our discussion in the telco yesterday, we would simply like to make sure that we all have the same understanding of the semantics and the utilization of milestones/phases in BCF topics, before we add this into the next version of the BCF standard. 

1) When we speak about milestones or phases, do they (in both cases) all refer to the typical BIM project phases/stages (i.e. in this "milestone/phase" field we should expect typical values like "Conceptual", "Preliminary Design", "Detailed Planning", "Construction", "As-built", etc.)? And that they do NOT refer to any sub-level milestones/phases, like "Construction phase I" or "Construction phase II", etc. ?


2) If we are going to take "phase" instead of "milestone" as the name of this field in order to mirror the "phase" property in .ifc files, are we sure that in .ifc files the "phase" property refers to the same typical BIM project phases/stages? (please pardon my scarce knowledge on the usage of phase property in .ifc files)


3) If a BCF topic is assigned with a specific "phase", does it mean that this BCF topic originate from this "phase" or does it indicate that this BCF topic should be resolved (i.e. end-of-life) within this "phase"?


4) Both "milestone/phase" and "due date" in the schema imply time constraints on a BCF topic, what would be the desired interplay between these two fields, when it comes to resolving conflicting values in them?


Any input and suggestion is welcomed here. 

Cheers

**Comment by ErikPijnenburg** [comment]
Let me share my idea's when I put this property forward as reaction on your points:
1) They can refer to any level of milestones/phases a user chooses.
2) I suggested Milestones precisely to seperate it from the IFC phases.
3) It indicates the issue needs to be finalized in this Milestone.
4) Due-date has priority above Milestone start-date/completion-date

**Comment by mullerlele** [comment]
@ErikPijnenburg Thank you very much for contributing to the discussion. FYI, the idea of renaming "Milestone" to "Phase" came up in the last telco, and was about to be merged into the v2.1 as "Phase". However, I found the semantic of "Phase" is different from that of "Milestone" (esp. in the context of mirroring ifc phases), and quite different from what you have originally proposed. Hence I have suggested to postpone the merge and have a discussion about it on Github here before final decision is made.

**Comment by ErikPijnenburg** [comment]
No problem to have a discussion. In my view we should not mixup Phase as intended in .ifc for objects with Milestone as intended/needed in issue-management. Two different concepts

**Comment by ErikPijnenburg** [comment]
In last Telco was suggested to change name into phase. I oppose to that. A phase is something else as a Milestone. The last one clearly indicates a deadline-possibility for issues, which is exactly what I meant with my proposal. The name "phase" is moving away from my original goal here...

**Comment by GeorgDangl** [comment]
I did actually change the name from "milestone" to "stage". This was discussed in the call on October 24th, 2016. I wasn't attending, but that's what the minutes said=)

**Comment by ErikPijnenburg** [comment]
stage/phase, both are not what I meant with Milestone.

**Pull request merged**
