### PR TITLE
Change user_id_type --> user

### PR DESCRIPTION
**Pull request by jasollien**

### CODE REVIEW

**Comment by ykulbak** [comment]
@jasollien I believe you missed line 75, can you please check?

**Review by ykulbak — CHANGES_REQUESTED** [review]
Check out line 75

**Comment by jasollien** [comment]
@ykulbak, do you know if we need those "Extended..." items at all?

**Comment by jasollien** [comment]
Never mind my latest comment. Will be redundant after this change: https://github.com/buildingSMART/BCF-XML/pull/251

**Comment by ykulbak** [comment]
This pull request was obsoleted by #251

**Pull request closed without merging**
