### PR TITLE
Migrate test case Visualization->"Single invisible wall" to 3.0

### PR DESCRIPTION
**Pull request by leosobral**
Due to github issues: This PR needs to be used instead: https://github.com/buildingSMART/BCF-XML/pull/326

### CODE REVIEW

**Review by cschladetsch — COMMENTED** [review]
Punctuation at end of paragraphs and bullet points is inconsistent.

There is unneeded vertical white space.

**Comment by LionelOnTech** [comment]
TopicType missing in markup.bcf

**Comment by LionelOnTech** [comment]
Reviewed. Looks good for v3.0. Also verified .bcf file worked in Aconex.

**Review by pasi-paasiala — APPROVED** [review]
Imports fine to Solibri

**Pull request closed without merging**
