### PR TITLE
Include visibilityBase enumeration in visinfo

### PR DESCRIPTION
**Pull request by jasollien**

### CODE REVIEW

**Comment by ErikPijnenburg** [comment]
This is a suggestion for new BCF definition, and cannot be part of version 2.0 ?

**Comment by ErikPijnenburg** [comment]
Would it be possible to reach a decision on this matter soon ?
Currently there are two suggestions for solving this:

1) introducing a VisibilityBase like suggested above
2) Pasi's suggestion in #65 to export with visible=false and with color/selected information as new agreement to show all and select/color a few.

The first is (most clear). But does it change the definition ? If not then I am in fovor of moving forward with this one.

**Comment by jasollien** [comment]
Update: There should be three flags: 

1: "normal" components
2: Spaces
3: Openings

**Comment by jasollien** [comment]
Last update: https://docs.google.com/document/d/1_J1U8Uih1YpJf3RdgVV02NznQVO-zP3UCbU7Tc30Ymg/edit

**Comment by jasollien** [comment]
[BCF 2.pptx](https://github.com/BuildingSMART/BCF-XML/files/313421/BCF.2.pptx)

**Comment by linhard** [comment]
Delay to 3.0

**Pull request closed without merging**
